[package]
name = "APIron"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }
dotenv = "0.15"
tokio = { version = "1", features = ["full"] }
